<?php

namespace Onekone\Lore\Attributes;

use Attribute;
use Onekone\Lore\Attributes\TraitSchemas\RulesSchemaBuilder;
use OpenApi\Attributes as OA;
use OpenApi\Generator;
use PHPStan\BetterReflection\Reflection\Adapter\ReflectionClass;

#[Attribute(Attribute::TARGET_CLASS | Attribute::TARGET_METHOD | Attribute::TARGET_PROPERTY | Attribute::TARGET_PARAMETER | Attribute::IS_REPEATABLE)]
class FormRequestBody extends OA\RequestBody
{
    use RulesSchemaBuilder;

    public function validate(array $stack = [], array $skip = [], string $ref = '', $context = null): bool
    {
        if (($this->x['__undefined_class__'] ?? false)) {
            $ra = $this->_context->reflection_argument;


            /** @var \ReflectionParameter $ra */
            try {
                $p = new \ReflectionClass($ra->getType()->getName());
            } catch (\Throwable $throwable) {
                $p = null;
            }


            if ($p) {
                foreach ($p->getAttributes() as $attribute) {
                    if ($attribute->getName() == OA\RequestBody::class) {
                        parent::__construct(ref: '#/components/requestBodies/' . $attribute->getArguments()['request']);
                    }
                }
            }
        }

        return parent::validate($stack, $skip, $ref, $context); // TODO: Change the autogenerated stub
    }

    /**
     * @param class-string $class
     * @param string|null $request
     */
    public function __construct(?string $class = null, string $request = null)
    {
        if ($class == null) {
            return parent::__construct(
                ref: Generator::UNDEFINED,
                x: ['__undefined_class__' => true]
            );
        }

        return parent::__construct(
            ref: Generator::UNDEFINED,
            request: $request,
            description: $description ?? Generator::UNDEFINED,
            required: Generator::UNDEFINED,
            content: new JsonValidatorSchema($class),
            x: []
        );
    }
}
