<?php

namespace Onekone\Lore\Attributes;

use Attribute;
use OpenApi\Attributes as OA;
use OpenApi\Generator;

#[Attribute(Attribute::TARGET_CLASS | Attribute::TARGET_METHOD | Attribute::TARGET_PROPERTY | Attribute::TARGET_PARAMETER | Attribute::IS_REPEATABLE)]
class RouteParameter extends OA\PathParameter
{
    public $in = 'path';
    public $required = true;

    public function __construct(string $ref = null, array $x = [])
    {
        if (!$ref) {
            $x ['__undefined_class__'] = true;
        }
        return parent::__construct(
            ref: $ref ? (strpos($prefix = '#/components/parameters/') ? $ref : $prefix . $ref) : '#/components/parameters/unset',
            x: $x
        );
    }

    public function validate(array $stack = [], array $skip = [], string $ref = '', $context = null): bool
    {
        if ($this->x['__undefined_class__'] ?? false) {
            unset($this->x['__undefined_class__']);
            $this->ref = $this->_context->argument ? '#/components/parameters/' . $this->_context->argument : Generator::UNDEFINED;
        }

        return parent::validate($stack, $skip, $ref, $context); // TODO: Change the autogenerated stub
    }
}
